[package]
name = "somni"
version = "0.1.0"
edition = "2024"
rust-version = "1.87.0"

[[bench]]
name = "benchmark"
harness = false

[workspace.dependencies]
indexmap = "2.9.0"

[dependencies]
indexmap.workspace = true
somni-parser = { path = "somni-parser" }
somni-expr = { path = "somni-expr" }

[dev-dependencies]
criterion = "0.6"
ansi-parser = "0.9.0"
pretty_assertions = "1.4.1"

[profile.release]
debug = true

[workspace]
members = [
    ".",
    "xtask",
    "somni-parser",
    "somni-expr",
]
