[package]
name = "somni"
version = "0.1.0"
edition = "2024"
rust-version = "1.87.0"

[[bench]]
name = "benchmark"
harness = false

[dependencies]
indexmap = "2.9.0"
pretty_assertions = "1.4.1"

[dev-dependencies]
criterion = "0.6"
ansi-parser = "0.9.0"

[profile.release]
debug = true

[workspace]
members = [
    ".",
    "xtask",
]
