[package]
name = "somni"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.9.0"
pretty_assertions = "1.4.1"

[profile.release]
debug = true

[workspace]
members = [
    ".",
    "xtask",
]
