[package]
name = "somni-expr"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

[dependencies]
somni-parser = { path = "../somni-parser" }
indexmap.workspace = true

[dev-dependencies]
ansi-parser.workspace = true
pretty_assertions.workspace = true
